import AutoRunDefs as Adef
import tkinter as tk
class OSAutoRun(tk.Frame):
    def __init__(self, master):
        tk.Frame.__init__(self, master)
        self.pack(side='top',fill='both',expand=True)
        MainFrame=tk.Frame(self)
        MainFrame.pack(side='top',fill='both',expand=True)
        chkvar1=tk.BooleanVar()
        chkvar2=tk.BooleanVar()
        chkvar3=tk.BooleanVar()
        chkvar4=tk.BooleanVar()
        chkvar5=tk.BooleanVar()
        chkvar6=tk.BooleanVar()
        chkvar7=tk.BooleanVar()
        defaultframe=tk.LabelFrame(MainFrame,text='Default Settings', relief="ridge",font=('Malgun Gothic',18, 'bold'), bd=2)
        defaultframe.pack(side='left',fill='both')
        infoframe=tk.Frame(defaultframe)
        infoframe.pack(side='top',fill='both',expand=True)
        btframe=tk.Frame(defaultframe)
        btframe.pack(side='top',fill='both',expand=True)
        def defaultset():
            temp=Adef.sysdefault()
            chkbox1.config(text=f'Current: {temp[0]}')
            chkbox2.config(text=f'User Name: {temp[1]}')
            chkbox3.config(text=f'Current Update: {temp[2]}')
        def setlist():
            temp=Adef.defaultlist(chkvar1.get(),chkvar2.get(),chkvar3.get(),chkvar4.get(),chkvar5.get(),chkvar6.get(),chkvar7.get())
            Adef.runset(temp)
        #---------------------checkboxlist------------------------------
        chkbox1=tk.Checkbutton(infoframe,var=chkvar1,font=('Malgun Gothic', 13, 'bold'))
        chkbox1.select()
        chkbox1.grid(row=0,column=0,sticky='w')
        chkbox2=tk.Checkbutton(infoframe,text='',var=chkvar2,font=('Malgun Gothic', 13, 'bold'))
        chkbox2.select()
        chkbox2.grid(row=2,column=0,sticky='w')
        chkbox3=tk.Checkbutton(infoframe,var=chkvar3,font=('Malgun Gothic', 13, 'bold'))
        chkbox3.select()
        chkbox3.grid(row=4,column=0,sticky='w')
        chkbox4=tk.Checkbutton(infoframe,var=chkvar4,font=('Malgun Gothic', 13, 'bold'))
        chkbox4.select()
        chkbox4.grid(row=6,column=0,sticky='w')
        chkbox5=tk.Checkbutton(infoframe,var=chkvar5,font=('Malgun Gothic', 13, 'bold'))
        chkbox5.select()
        chkbox5.grid(row=8,column=0,sticky='w')
        chkbox6=tk.Checkbutton(infoframe,var=chkvar6,font=('Malgun Gothic', 13, 'bold'))
        chkbox6.select()
        chkbox6.grid(row=10,column=0,sticky='w')
        chkbox7=tk.Checkbutton(infoframe,var=chkvar7,font=('Malgun Gothic', 13, 'bold'))
        chkbox7.select()
        chkbox7.grid(row=12,column=0,sticky='w')
        #---------------------checkboxlabels------------------------------
        label1=tk.Label(infoframe,text='Power Saving Mode Off Set',font=('Malgun Gothic', 13, 'bold'),justify='left')
        label1.grid(row=0,column=1,sticky='w')
        label2=tk.Label(infoframe,text='User Account Control Set',font=('Malgun Gothic', 13, 'bold'),justify='left')
        label2.grid(row=2,column=1,sticky='w')
        label2=tk.Label(infoframe,text='Windows Update Disable',font=('Malgun Gothic', 13, 'bold'),justify='left')
        label2.grid(row=4,column=1,sticky='w')
        exlabel1=tk.Label(infoframe,text='절전모드를 "고성능"그룹으로 설정하고 아래설정을 해제합니다\n(절전모드, 모니터꺼짐, 모니터자동밝기, 디스크절전모드, USB절전모드)',font=('Malgun Gothic', 10, 'bold'))
        exlabel1.grid(row=1,column=0,columnspan=2)
        exlabel2=tk.Label(infoframe,text='사용자를 관리자로 설정하고 알림설정을 해제합니다',font=('Malgun Gothic', 10, 'bold'))
        exlabel2.grid(row=3,column=0,columnspan=2)
        exlabel3=tk.Label(infoframe,text='윈도우 업데이트설정을 해제하고 관련된 아래설정을 해제합니다\n(Health Service, Windows Update, Medic Service, Orchestrator)',font=('Malgun Gothic', 10, 'bold'))
        exlabel3.grid(row=5,column=0,columnspan=2)
        
        setbt=tk.Button(btframe,text='Set',font=('Malgun Gothic', 13, 'bold'),command=setlist)
        setbt.pack()
        defaultset()
        
    
        